/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthedImport } from './routes/_authed'
import { Route as IndexImport } from './routes/index'
import { Route as PortalTokenImport } from './routes/portal.$token'
import { Route as AuthedSettingsImport } from './routes/_authed/settings'
import { Route as AuthedReportsImport } from './routes/_authed/reports'
import { Route as AuthedProductsImport } from './routes/_authed/products'
import { Route as AuthedOrdersImport } from './routes/_authed/orders'
import { Route as AuthedLedgerImport } from './routes/_authed/ledger'
import { Route as AuthedInvoicesImport } from './routes/_authed/invoices'
import { Route as AuthedExpensesImport } from './routes/_authed/expenses'
import { Route as AuthedDashboardImport } from './routes/_authed/dashboard'
import { Route as AuthedCustomersImport } from './routes/_authed/customers'
import { Route as AuthedAssetsImport } from './routes/_authed/assets'
import { Route as AuthedAgreementsImport } from './routes/_authed/agreements'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PortalTokenRoute = PortalTokenImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRoute,
} as any)

const AuthedSettingsRoute = AuthedSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedReportsRoute = AuthedReportsImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedProductsRoute = AuthedProductsImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedOrdersRoute = AuthedOrdersImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedLedgerRoute = AuthedLedgerImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedInvoicesRoute = AuthedInvoicesImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedExpensesRoute = AuthedExpensesImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedDashboardRoute = AuthedDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedCustomersRoute = AuthedCustomersImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedAssetsRoute = AuthedAssetsImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedAgreementsRoute = AuthedAgreementsImport.update({
  id: '/agreements',
  path: '/agreements',
  getParentRoute: () => AuthedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authed/agreements': {
      id: '/_authed/agreements'
      path: '/agreements'
      fullPath: '/agreements'
      preLoaderRoute: typeof AuthedAgreementsImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/assets': {
      id: '/_authed/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AuthedAssetsImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/customers': {
      id: '/_authed/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthedCustomersImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/expenses': {
      id: '/_authed/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthedExpensesImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/invoices': {
      id: '/_authed/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthedInvoicesImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/ledger': {
      id: '/_authed/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof AuthedLedgerImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/orders': {
      id: '/_authed/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthedOrdersImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/products': {
      id: '/_authed/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthedProductsImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/reports': {
      id: '/_authed/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthedReportsImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsImport
      parentRoute: typeof AuthedImport
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface AuthedRouteChildren {
  AuthedAgreementsRoute: typeof AuthedAgreementsRoute
  AuthedAssetsRoute: typeof AuthedAssetsRoute
  AuthedCustomersRoute: typeof AuthedCustomersRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedExpensesRoute: typeof AuthedExpensesRoute
  AuthedInvoicesRoute: typeof AuthedInvoicesRoute
  AuthedLedgerRoute: typeof AuthedLedgerRoute
  AuthedOrdersRoute: typeof AuthedOrdersRoute
  AuthedProductsRoute: typeof AuthedProductsRoute
  AuthedReportsRoute: typeof AuthedReportsRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAgreementsRoute: AuthedAgreementsRoute,
  AuthedAssetsRoute: AuthedAssetsRoute,
  AuthedCustomersRoute: AuthedCustomersRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedExpensesRoute: AuthedExpensesRoute,
  AuthedInvoicesRoute: AuthedInvoicesRoute,
  AuthedLedgerRoute: AuthedLedgerRoute,
  AuthedOrdersRoute: AuthedOrdersRoute,
  AuthedProductsRoute: AuthedProductsRoute,
  AuthedReportsRoute: AuthedReportsRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/agreements': typeof AuthedAgreementsRoute
  '/assets': typeof AuthedAssetsRoute
  '/customers': typeof AuthedCustomersRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/expenses': typeof AuthedExpensesRoute
  '/invoices': typeof AuthedInvoicesRoute
  '/ledger': typeof AuthedLedgerRoute
  '/orders': typeof AuthedOrdersRoute
  '/products': typeof AuthedProductsRoute
  '/reports': typeof AuthedReportsRoute
  '/settings': typeof AuthedSettingsRoute
  '/portal/$token': typeof PortalTokenRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/agreements': typeof AuthedAgreementsRoute
  '/assets': typeof AuthedAssetsRoute
  '/customers': typeof AuthedCustomersRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/expenses': typeof AuthedExpensesRoute
  '/invoices': typeof AuthedInvoicesRoute
  '/ledger': typeof AuthedLedgerRoute
  '/orders': typeof AuthedOrdersRoute
  '/products': typeof AuthedProductsRoute
  '/reports': typeof AuthedReportsRoute
  '/settings': typeof AuthedSettingsRoute
  '/portal/$token': typeof PortalTokenRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/agreements': typeof AuthedAgreementsRoute
  '/_authed/assets': typeof AuthedAssetsRoute
  '/_authed/customers': typeof AuthedCustomersRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/expenses': typeof AuthedExpensesRoute
  '/_authed/invoices': typeof AuthedInvoicesRoute
  '/_authed/ledger': typeof AuthedLedgerRoute
  '/_authed/orders': typeof AuthedOrdersRoute
  '/_authed/products': typeof AuthedProductsRoute
  '/_authed/reports': typeof AuthedReportsRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/portal/$token': typeof PortalTokenRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/agreements'
    | '/assets'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/invoices'
    | '/ledger'
    | '/orders'
    | '/products'
    | '/reports'
    | '/settings'
    | '/portal/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/agreements'
    | '/assets'
    | '/customers'
    | '/dashboard'
    | '/expenses'
    | '/invoices'
    | '/ledger'
    | '/orders'
    | '/products'
    | '/reports'
    | '/settings'
    | '/portal/$token'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/agreements'
    | '/_authed/assets'
    | '/_authed/customers'
    | '/_authed/dashboard'
    | '/_authed/expenses'
    | '/_authed/invoices'
    | '/_authed/ledger'
    | '/_authed/orders'
    | '/_authed/products'
    | '/_authed/reports'
    | '/_authed/settings'
    | '/portal/$token'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalTokenRoute: typeof PortalTokenRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalTokenRoute: PortalTokenRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authed",
        "/login",
        "/portal/$token"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/agreements",
        "/_authed/assets",
        "/_authed/customers",
        "/_authed/dashboard",
        "/_authed/expenses",
        "/_authed/invoices",
        "/_authed/ledger",
        "/_authed/orders",
        "/_authed/products",
        "/_authed/reports",
        "/_authed/settings"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authed/agreements": {
      "filePath": "_authed/agreements.tsx",
      "parent": "/_authed"
    },
    "/_authed/assets": {
      "filePath": "_authed/assets.tsx",
      "parent": "/_authed"
    },
    "/_authed/customers": {
      "filePath": "_authed/customers.tsx",
      "parent": "/_authed"
    },
    "/_authed/dashboard": {
      "filePath": "_authed/dashboard.tsx",
      "parent": "/_authed"
    },
    "/_authed/expenses": {
      "filePath": "_authed/expenses.tsx",
      "parent": "/_authed"
    },
    "/_authed/invoices": {
      "filePath": "_authed/invoices.tsx",
      "parent": "/_authed"
    },
    "/_authed/ledger": {
      "filePath": "_authed/ledger.tsx",
      "parent": "/_authed"
    },
    "/_authed/orders": {
      "filePath": "_authed/orders.tsx",
      "parent": "/_authed"
    },
    "/_authed/products": {
      "filePath": "_authed/products.tsx",
      "parent": "/_authed"
    },
    "/_authed/reports": {
      "filePath": "_authed/reports.tsx",
      "parent": "/_authed"
    },
    "/_authed/settings": {
      "filePath": "_authed/settings.tsx",
      "parent": "/_authed"
    },
    "/portal/$token": {
      "filePath": "portal.$token.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
