/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthedImport } from './routes/_authed'
import { Route as IndexImport } from './routes/index'
import { Route as AuthedRelatoriosImport } from './routes/_authed/relatorios'
import { Route as AuthedProdutosImport } from './routes/_authed/produtos'
import { Route as AuthedPedidosImport } from './routes/_authed/pedidos'
import { Route as AuthedInvoicesImport } from './routes/_authed/invoices'
import { Route as AuthedDashboardImport } from './routes/_authed/dashboard'
import { Route as AuthedConfiguracoesImport } from './routes/_authed/configuracoes'
import { Route as AuthedClientesImport } from './routes/_authed/clientes'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRelatoriosRoute = AuthedRelatoriosImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedProdutosRoute = AuthedProdutosImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedPedidosRoute = AuthedPedidosImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedInvoicesRoute = AuthedInvoicesImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedDashboardRoute = AuthedDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedConfiguracoesRoute = AuthedConfiguracoesImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AuthedRoute,
} as any)

const AuthedClientesRoute = AuthedClientesImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authed/clientes': {
      id: '/_authed/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthedClientesImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/configuracoes': {
      id: '/_authed/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthedConfiguracoesImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/invoices': {
      id: '/_authed/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthedInvoicesImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/pedidos': {
      id: '/_authed/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthedPedidosImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/produtos': {
      id: '/_authed/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthedProdutosImport
      parentRoute: typeof AuthedImport
    }
    '/_authed/relatorios': {
      id: '/_authed/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthedRelatoriosImport
      parentRoute: typeof AuthedImport
    }
  }
}

// Create and export the route tree

interface AuthedRouteChildren {
  AuthedClientesRoute: typeof AuthedClientesRoute
  AuthedConfiguracoesRoute: typeof AuthedConfiguracoesRoute
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedInvoicesRoute: typeof AuthedInvoicesRoute
  AuthedPedidosRoute: typeof AuthedPedidosRoute
  AuthedProdutosRoute: typeof AuthedProdutosRoute
  AuthedRelatoriosRoute: typeof AuthedRelatoriosRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedClientesRoute: AuthedClientesRoute,
  AuthedConfiguracoesRoute: AuthedConfiguracoesRoute,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedInvoicesRoute: AuthedInvoicesRoute,
  AuthedPedidosRoute: AuthedPedidosRoute,
  AuthedProdutosRoute: AuthedProdutosRoute,
  AuthedRelatoriosRoute: AuthedRelatoriosRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/clientes': typeof AuthedClientesRoute
  '/configuracoes': typeof AuthedConfiguracoesRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/invoices': typeof AuthedInvoicesRoute
  '/pedidos': typeof AuthedPedidosRoute
  '/produtos': typeof AuthedProdutosRoute
  '/relatorios': typeof AuthedRelatoriosRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/clientes': typeof AuthedClientesRoute
  '/configuracoes': typeof AuthedConfiguracoesRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/invoices': typeof AuthedInvoicesRoute
  '/pedidos': typeof AuthedPedidosRoute
  '/produtos': typeof AuthedProdutosRoute
  '/relatorios': typeof AuthedRelatoriosRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/clientes': typeof AuthedClientesRoute
  '/_authed/configuracoes': typeof AuthedConfiguracoesRoute
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/invoices': typeof AuthedInvoicesRoute
  '/_authed/pedidos': typeof AuthedPedidosRoute
  '/_authed/produtos': typeof AuthedProdutosRoute
  '/_authed/relatorios': typeof AuthedRelatoriosRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/invoices'
    | '/pedidos'
    | '/produtos'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/invoices'
    | '/pedidos'
    | '/produtos'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/clientes'
    | '/_authed/configuracoes'
    | '/_authed/dashboard'
    | '/_authed/invoices'
    | '/_authed/pedidos'
    | '/_authed/produtos'
    | '/_authed/relatorios'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authed",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authed": {
      "filePath": "_authed.tsx",
      "children": [
        "/_authed/clientes",
        "/_authed/configuracoes",
        "/_authed/dashboard",
        "/_authed/invoices",
        "/_authed/pedidos",
        "/_authed/produtos",
        "/_authed/relatorios"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authed/clientes": {
      "filePath": "_authed/clientes.tsx",
      "parent": "/_authed"
    },
    "/_authed/configuracoes": {
      "filePath": "_authed/configuracoes.tsx",
      "parent": "/_authed"
    },
    "/_authed/dashboard": {
      "filePath": "_authed/dashboard.tsx",
      "parent": "/_authed"
    },
    "/_authed/invoices": {
      "filePath": "_authed/invoices.tsx",
      "parent": "/_authed"
    },
    "/_authed/pedidos": {
      "filePath": "_authed/pedidos.tsx",
      "parent": "/_authed"
    },
    "/_authed/produtos": {
      "filePath": "_authed/produtos.tsx",
      "parent": "/_authed"
    },
    "/_authed/relatorios": {
      "filePath": "_authed/relatorios.tsx",
      "parent": "/_authed"
    }
  }
}
ROUTE_MANIFEST_END */
